# Generated by Django 4.2.5 on 2023-10-30 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('posicao', models.CharField(max_length=50)),
                ('n_camisa', models.IntegerField()),
                ('cartoes_v', models.IntegerField()),
                ('cartoes_a', models.IntegerField()),
                ('pe', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('altura', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gols_mandante', models.IntegerField()),
                ('gols_visitante', models.IntegerField()),
                ('data', models.DateTimeField()),
                ('rodada', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('nome', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tecnico', models.CharField(max_length=50)),
                ('vitorias', models.IntegerField()),
                ('derrotas', models.IntegerField()),
                ('empates', models.IntegerField()),
                ('gols_s', models.IntegerField()),
                ('gols_m', models.IntegerField()),
                ('estadio', models.CharField(max_length=50)),
                ('escudo', models.ImageField(upload_to='escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='Substituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador_entrou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicao_entrou', to='main.jogador')),
                ('jogador_saiu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituicao_saiu', to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
        ),
        migrations.AddField(
            model_name='partida',
            name='time_mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_mandante', to='main.time'),
        ),
        migrations.AddField(
            model_name='partida',
            name='time_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_visitante', to='main.time'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.time'),
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jogador_ass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistencias', to='main.jogador')),
                ('jogador_gol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gols_feitos', to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
        ),
        migrations.CreateModel(
            name='JogadorPartida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cartoes_amarelos', models.IntegerField(default=0)),
                ('cartoes_vermelhos', models.IntegerField(default=0)),
                ('faltas_cometidas', models.IntegerField(default=0)),
                ('assistencias', models.IntegerField(default=0)),
                ('finalizacoes', models.IntegerField(default=0)),
                ('passes', models.IntegerField(default=0)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.jogador')),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.partida')),
            ],
            options={
                'unique_together': {('jogador', 'partida')},
            },
        ),
    ]
